<!DOCTYPE html>

<html lang="en-US">

	<head>
		<meta charset="utf-8">
	</head>
	
	<body>
	
		You now have access to The Asterisk App. 
		
		<br>
		<hr>
		
		(This message was automatically generated by The Asterisk App.)
		
	</body>
	
</html>
