<!DOCTYPE html>

<html lang="en-US">

	<head>
		<meta charset="utf-8">
	</head>
	
	<body>
	
		{!! $name !!} with email {!! $email !!} has registered and requires approval. 
		
		<br>
		<hr>
		
		(This message was automatically generated by The Asterisk App.)
		
	</body>
	
</html>
